[project]
name = "c0mpiled-psu"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flax>=0.12.4",
    "jax[cuda13]>=0.9.0.1",
    "jupyter>=1.1.1",
    "numpy>=2.3.5",
    "torch>=2.10.0",
]
